Repository CarbonEye/CE_Front, pull requests merged in 2023-05, with the labels that each got.

#15 API 관련 함수 작성 및 Token 저장 함수 작성
  jsconfig.json
  src/API/account.jsx
  src/API/email.jsx
  src/API/group.jsx
  src/API/index.jsx
  src/API/traffic.jsx
  src/App.js
  src/utils/localStorage.js
Labels: feat, fix, API

#16 Code Convention에 맞지 않는 부분에 prettier적용 및 에러 수정
  src/App.js
  src/Components/Login/LoginForm.jsx
  src/Components/MyCertification/CertificationPage.jsx
  src/Components/MyPage/MyPage.jsx
  src/Components/MyPage/ReportPage.jsx
  src/Components/Signup/SignUp.jsx
Labels: fix, styling

#17 Group Rank 개발 및 에러 수정
  src/App.js
  src/Components/Group/group.jsx
  src/Components/GroupRanking/GroupRanking.jsx
Labels: feat

#18 MainPage개발 및 Styling과 error수정
  src/API/main.js
  src/Components/Main/Main.jsx
  src/Components/index.jsx
  src/Components/login.jsx
  src/utils/months.js
Labels: bug, feat, fix

#19 Traffic Page에 대한 총괄적인 Refactoring
  src/App.js
  src/Components/Traffic/TrafficSolution.jsx
  src/Components/Traffic/traffic.jsx
  src/Components/Traffic/traffic.scss
  src/assets/Line.png
Labels: feat, fix, styling

#20 Login Component 수정
  src/App.js
  src/Components/Login/Login.jsx
  src/Components/Login/Login.scss
  src/Components/Login/LoginForm.css
  src/Components/Login/LoginForm.jsx
Labels: feat, fix

#21 회원가입 페이지 수정
  src/App.js
  src/Components/Register/register.jsx
Labels: feat, fix, API, styling

#22 공통적으로 사용되는 Header에 대한 구현
  src/App.js
  src/Components/Header/Header.jsx
  src/Components/Signup/SignUp.css
  src/Components/Signup/SignUp.jsx
Labels: feat, fix, styling

#23 1일차 API 연동
  src/API/account.jsx
  src/API/email.jsx
  src/API/traffic.jsx
  src/Components/Login/Login.jsx
  src/Components/Main/Main.jsx
  src/Components/Register/register.jsx
  src/Components/Traffic/TrafficSolution.jsx
  src/Components/Traffic/traffic.jsx
  src/Components/Traffic/trafficCarbon.jsx
Labels: bug, fix, API

#24 Home Component 추가 및 이에따른 Router와 Header 변경사항 수정
  src/App.js
  src/Components/Header/Header.jsx
  src/Components/Home/Home.jsx
Labels: feat, styling

#25 useEffect Hook을 통해 API 호출에서 무한루프를 도는 것을 방지
  src/Components/Main/Main.jsx
Labels: bug, fix

#26 GroupMember 페이지 생성 및 Fix, Refactoring 진행
  src/API/account.jsx
  src/App.js
  src/Components/GroupMember/Member.jsx
  src/Components/Login/Login.jsx
  src/Components/MyPage/MyPage.jsx
  src/Components/Register/register.jsx
Labels: feat, fix, API

#28 회의록에 있는 API 연동
  src/API/account.jsx
  src/API/group.jsx
  src/Components/GroupCreate/groupCreate.jsx
  src/Components/GroupJoin/groupJoin.jsx
  src/Components/Main/Main.jsx
  src/Components/MyCertification/CertificationPage.css
  src/Components/MyCertification/CertificationPage.jsx
  src/Components/MyCertification/CertificationPage.scss
  src/Components/MyPage/MyPage.jsx
  src/Components/MyPage/ReportPage.jsx
Labels: feat, fix, API

#30 Conflict 처리 및 invite Code를 Local Storage에 저장
  package-lock.json
  package.json
  src/API/account.jsx
  src/API/group.jsx
  src/Components/GroupCreate/groupCreate.jsx
  src/Components/GroupJoin/groupJoin.jsx
  src/Components/Main/Main.jsx
  src/Components/MyCertification/CertificationPage.css
  src/Components/MyCertification/CertificationPage.jsx
  src/Components/MyCertification/CertificationPage.scss
  src/Components/MyPage/MyPage.jsx
  src/Components/MyPage/ReportPage.jsx
Labels: feat, fix

#32 Food관련 Component들 생성
  src/API/food.js
  src/App.js
  src/Components/Food/Food.jsx
  src/Components/Food/Food.scss
  src/Components/Food/FoodSolution.jsx
  src/Components/Main/Main.jsx
  src/assets/camera.png
Labels: feat, API, styling

#34 docs: ceertification API연결 코드 추가, API폴더에 img.jsx 파일 새로 생성
  src/API/img.jsx
  src/Components/MyCertification/CertificationPage.jsx
Labels: feat, fix

#35 5월 23일자 refactoring 및 api 연동
  src/API/cert.js
  src/API/food.js
  src/App.js
  src/Components/Food/Food.jsx
  src/Components/GroupRanking/GroupRanking.jsx
  src/Components/MyCertification/CertificationPage.jsx
  src/Components/MyPage/ReportPage.jsx
Labels: feat, fix, API

#37 이미지를 서버에 전송 및 받아오기 연동
  src/Components/MyCertification/CertificationPage.jsx
  src/Components/Traffic/traffic.jsx
  src/Components/Traffic/traffic.scss
  src/Components/Traffic/trafficCarbon.jsx
Labels: feat, fix, API
