Repository CarbonEye/CE_Front, pull requests merged in 2023-03, with the labels that each got.

#1 Feat/traffic
  .gitignore
  package-lock.json
  package.json
  src/Components/traffic.jsx
  src/Components/traffic.scss
Labels: feat

#2 Feat/traffic2
  public/index.html
  src/Components/calculateTime.js
  src/Components/traffic.jsx
Labels: feat

#3 탄소발자국을 계산해주는 API 개발 및 컴포넌트 연동화 완료
  src/Components/calculateTime.js
  src/Components/traffic.jsx
  src/Components/trafficCarbon.jsx
Labels: feat, API

#8 chore: component들을 Directory로 관리하고자 파일 이동
  src/Components/Traffic/traffic.jsx
  src/Components/Traffic/traffic.scss
  src/Components/Traffic/trafficCarbon.jsx
Labels: fix

#9 Feat/group1
  src/App.js
  src/Components/Group/group.jsx
  src/Components/Group/group.scss
  src/Components/NotFound/notFound.jsx
  src/Components/Traffic/calculateTime.js
  src/Components/Traffic/traffic.jsx
Labels: feat

#6 feat: SignUp
  src/Components/Signup/SignUp.jsx
Labels: feat
